### ISSUE TITLE
show the version number of the dependency

### ISSUE THREAD

**Issue by ritikbheda** [npmhub/npmhub#145] opened 2021-10-13 00:37 UTC
We already have dependency name but adding its version number would be a good feature added I think. What do you guys think?

Something like what Dependency graph shows:
![DependencyGraph](https://user-images.githubusercontent.com/60680215/137047348-8c21151e-f48f-4eb6-ab34-9eec12e2b4d4.JPG)

Link to Dependency graph: [here](https://github.com/npmhub/npmhub/network/dependencies)

**Comment by fregante** [comment] 2021-10-13 05:25
Duplicate of https://github.com/npmhub/npmhub/issues/56

**Comment by fregante** [comment] 2023-12-20 09:36
I'm reverting to my previous opinion. 

I don't want to show this information here because then I'd also have to use that specific version's `description` instead of the latest version's, which is always "better."

If you need this, just open the package.json.

**Closed by fregante** 2023-12-20 09:36 UTC
Labels: enhancement, help wanted
